### ISSUE TITLE
Allow a custom timeout on the requests

### ISSUE THREAD

**Issue by ripienaar** [dkhamsing/awesome_bot#10]
Some times some site is down temporarily which makes checks fail and do so very slowly.

Would be good to have an option to tweak the timeout and also to decide if timeouts are critical or not.  I wouldnt want to fail a test on a PR due to a timeout but would periodically do a overall check with that set to fail

**Comment by dkhamsing** [comment]
Hm will think about this

**Comment by dkhamsing** [comment]
How about two options 

- `--set-timeout`, i.e. `--set-timeout 5`
- `--allow-timeout`

What do you think

**Comment by ripienaar** [comment]
that seems good yeah

**Comment by dkhamsing** [comment]
@ripienaar I have an update with these options (on a branch), hope you don't mind but I will open a pr on your repo to test this..
