### ISSUE TITLE
Incomplete Redirects

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/awesome_bot#106]
When redirects do not contain the full path, `awesome_bot` should try to correct that

```
 https://godoc.org/github.com/ipfs/go-libp2p-crypto  → /github.com/libp2p/go-libp2p-crypto 
```

Reported on https://github.com/dkhamsing/frankenstein/issues/18

**Comment by dkhamsing** [comment]
cc @RichardLitt

**Comment by RichardLitt** [comment]
Sounds good. Thanks.

**Comment by RichardLitt** [comment]
Can I whitelist urls to make this not come up?

**Comment by dkhamsing** [comment]
I suppose
Got a fix that should be merged soon

**Comment by dkhamsing** [comment]
FYI white list doesn't fix this problem, just ignores it

**Comment by RichardLitt** [comment]
Yep. Might be best if I just whitelist unpkg, as it redirects to the newest version number, which we don't want (in my particular use case). 

Thank you, again.
