### ISSUE TITLE
Issue with using master branch

### ISSUE THREAD

**Issue by RichardLitt** [dkhamsing/awesome_bot#108]
I got a PR which isn't reflective of what the bot is supposed to do, here: https://github.com/libp2p/js-peer-info/pull/24. I think this is an issue with previously existing, out-of-date master branch, but I'm not sure. What do you think? 

Why are we using `master`, at all? Wouldn't it make more sense to open a new branch on the fork for the readme edits, so that they don't make master stale if there is more development on it?

**Comment by dkhamsing** [comment]
Do you mean about the incomplete redirects? That has not been merged yet

**Comment by RichardLitt** [comment]
Nope; take a look at the changed files. I'm not sure there were so many other changes? https://github.com/libp2p/js-peer-info/pull/24/files

**Comment by dkhamsing** [comment]
Oh I see

Good suggestion ! 

Basically the tool should check that the fork is up to date..

By the way, this is an issue on Frankenstein 😁 

I will open it

**Comment by RichardLitt** [comment]
@dkhamsing Thanks!  And ah, darn. I was trying to be clever. My bad. :)
