### ISSUE TITLE
Just saying

### ISSUE THREAD

**Issue by Stephn-R** [dkhamsing/awesome_bot#11]
This is a pretty simple/cool project

**Comment by dkhamsing** [comment]
Cool
Let me know if it can be improved or what not

**Comment by zeke** [comment]
:sunglasses:

**Comment by dkhamsing** [comment]
@zeke hey there :smile:

**Comment by huei90** [comment]
Simple but useful project :books:

**Comment by dkhamsing** [comment]
@huei90 thanks!
