### ISSUE TITLE
Dot is parsed as part of implicit links

### ISSUE THREAD

**Issue by stoyicker** [dkhamsing/awesome_bot#112]
For example:

`[Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation).`, which is used to render [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), results in awesome_bot checking [(https://en.wikipedia.org/wiki/Hungarian_notation.)] dot included, which is incorrect (and in this case a 404).

While I'm putting a newline character between the link and the dot as a workaround to allow my PRs to pass CI while minimising the visual impact on what the markdown generates, I shouldn't need to do this.

**Comment by dkhamsing** [comment]
thanks for the report!

**Comment by dkhamsing** [comment]
Should be fixed in `1.13.9`
