### ISSUE TITLE
How do I check all the markdown files?

### ISSUE THREAD

**Issue by lanceplaine** [dkhamsing/awesome_bot#118]
When I use `*.md` it only check the `.md` files at the root folder.

I would like to check all the markdown files including the one in the folders.

Thanks

**Comment by dkhamsing** [comment]
noted
if you can compute a list of files to check, you can pass them in with `-f`

otherwise this is not possible at the moment

**Comment by lanceplaine** [comment]
Ok thanks.
This feature would be great

**Comment by m1guelpf** [comment]
@lanceplaine You could try to do:
for d in ./*/ ; do (cd "$d" && awesome-bot *.md); done

**Comment by lanceplaine** [comment]
@m1guelpf: I tried your code but it doesn't seems to work as it. Do you mind sharing the entire `.travis.yml` config you used? Did you tested theses lines? 
Thanks :)

**Comment by m1guelpf** [comment]
@lanceplaine That is a little bash trick for running a command with every file in every folder. I did not test it for this custom use, but it should work.
Try adding it to something like test.sh and running it trougth .travis.yml

**Comment by dkhamsing** [comment]
can u put that in a shell script, maybe try locally

**Comment by m1guelpf** [comment]
@dkhamsing Just said that :laughing:

**Comment by dkhamsing** [comment]
Closing this for now
Thx @m1guelpf for the workaround

**Comment by davidhrbac** [comment]
You can use something like this
```bash
find . -name '*.md' -exec grep -l http {} + | xargs awesome_bot
```
