### ISSUE TITLE
Check links with relative URLs

### ISSUE THREAD

**Issue by lanceplaine** [dkhamsing/awesome_bot#119]
It would be great if the `gem` could check the images URLs in a markdown file.

Example: `![Image name](path/to/image)`.

Is this something you plan on adding?

**Comment by dkhamsing** [comment]
it should do this now, if the path is a full url

i.e. `![image name](https://media4.giphy.com/media/l0MYF82iiI4hNVqa4/200_s.gif)`

**Comment by lanceplaine** [comment]
Thanks fo your quick answer @dkhamsing 

What about relative URLs? Is there an option to check them. Because 95% of my images are relative URLs

**Comment by dkhamsing** [comment]
yea that is not supported 😓

**Comment by lanceplaine** [comment]
Ah ok. 
It would be great.
Thanks

**Comment by sidewinder12s** [comment]
Could a flag be added to pass in a baseurl for testing during integration?

**Comment by dkhamsing** [comment]
This baseurl would apply to every links??

**Comment by sidewinder12s** [comment]
Only relative links.

**Comment by dkhamsing** [comment]
I guess that's reasonable. 
Do you have time to work on this?

**Comment by sidewinder12s** [comment]
I haven't really developed ruby at all, figured I'd throw in a possible solution for relative urls :)

Might take a swing if I get time.

**Comment by dkhamsing** [comment]
@lanceplaine can u provide a file example?

**Comment by joshmoore** [comment]
I'm trying to achieve this at the moment as well (https://github.com/IDR/idr-notebooks/pull/2) with the use case being that I'd like to make sure that the pointers in the README to internal files are not broken.

**Comment by dkhamsing** [comment]
@joshmoore were you able to catch your internal files when converting to html (with redcarpet) ?

**Comment by joshmoore** [comment]
I was but the URLs are still relative:

```
<li><strong><a href="notebooks/Getting_Started.ipynb">Getting Started</a></strong>: How to connect, some simple data access
```

and don't appear to be checked in the travis output:

https://travis-ci.org/IDR/idr-notebooks/builds/233143900

(p.s. apologies there was a cut-n-paste error in my previous comment. PR 2 was supposed to be PR 20. I've fixed it now.)

**Comment by dkhamsing** [comment]
@joshmoore work in progress

```sh
$awesome_bot README.md 
> Checking links in README.md
Links to check: 13
  01. https://idr.openmicroscopy.org 
  02. https://www.openmicroscopy.org/site/support/omero5.2/developers/ 
  03. https://www.openmicroscopy.org/site/support/omero5.2/developers/Python.html 
  04. https://www.scipy.org/ 
  05. http://pandas.pydata.org 
  06. https://github.com/idr-contrib 
  07. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/Getting_Started.ipynb 
  08. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/IDR_API_example_script.ipynb 
  09. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/Figure_1_Sampling_of_Phenotypes.ipynb 
  10. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/GeneNetwork.ipynb 
  11. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/RohnPhenotypeClustering.ipynb 
  12. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/PCAanalysisOfCharmFeatures.ipynb 
  13. https://doi.org/10.1101/089359 
Checking URLs: ✓✓✓→→→→→→→✓
#...
```

New option `--base-url`

```
$ awesome_bot README.md --base-url https://github.com/IDR/idr-notebooks/blob/master/
> Checking links in README.md
> Will check relative links with base URL https://github.com/IDR/idr-notebooks/blob/master/
Links to check: 22, 21 unique
  01. https://github.com/IDR/idr-notebooks/blob/master//includes/login_1.png?raw=true "OAuth login" 
  02. https://github.com/IDR/idr-notebooks/blob/master/notebooks/Getting_Started.ipynb 
  03. https://github.com/IDR/idr-notebooks/blob/master/notebooks/IDR_API_example_script.ipynb 
  04. https://github.com/IDR/idr-notebooks/blob/master/notebooks/Figure_1_Sampling_of_Phenotypes.ipynb 
  05. https://github.com/IDR/idr-notebooks/blob/master/bokeh.pydata.org/ 
  06. https://github.com/IDR/idr-notebooks/blob/master/notebooks/GeneNetwork.ipynb 
  07. https://github.com/IDR/idr-notebooks/blob/master/notebooks/RohnPhenotypeClustering.ipynb 
  08. https://github.com/IDR/idr-notebooks/blob/master/notebooks/PCAanalysisOfCharmFeatures.ipynb 
  09. https://idr.openmicroscopy.org 
  10. https://www.openmicroscopy.org/site/support/omero5.2/developers/ 
  11. https://www.openmicroscopy.org/site/support/omero5.2/developers/Python.html 
  12. https://www.scipy.org/ 
  13. http://pandas.pydata.org 
  14. https://github.com/idr-contrib 
  15. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/Getting_Started.ipynb 
  16. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/IDR_API_example_script.ipynb 
  17. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/Figure_1_Sampling_of_Phenotypes.ipynb 
  18. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/GeneNetwork.ipynb 
  19. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/RohnPhenotypeClustering.ipynb 
  20. https://idr.openmicroscopy.org/jupyter/user/x/notebooks/notebooks/PCAanalysisOfCharmFeatures.ipynb 
  21. https://doi.org/10.1101/089359 
Checking URLs: ?x✓✓✓✓✓✓→✓✓✓✓→→→→→→→✓
#...
```

Note: `bokeh.pydata.org` will be flagged.. it should be added as `http://bokeh.pydata.org` in the README

What do you think?

**Comment by joshmoore** [comment]
`01` through `09` are certainly what I was looking for. I've just been looking at https://github.com/dkhamsing/frankenstein; if you think that `--base-url` is a clean addition to `awesome_bot` it certainly works for me. one thing it might _not_ permit is for a PR to be green when a file is added to the README since it will only exist on the PR. Perhaps travis has an environment variable which can be used for specifying `--base-url` that will correct for that.

**Comment by dkhamsing** [comment]
`frankenstein` is totally hacked together.. that it sorta works is a miracle

**Comment by dkhamsing** [comment]
@joshmoore can u explain how it would not work in a PR ? isn't the base URL static?

**Comment by dkhamsing** [comment]
what I mean is you are not checking the fork, but the original (your site)

**Comment by joshmoore** [comment]
> frankenstein is totally hacked together.. that it sorta works is a miracle

:) hence the name?

> isn't the base URL static?

So the scenario I'm thinking about is:

 * Travis regularly checks master with base-url https://github.com/IDR/idr-notebooks/blob/master/
 * I open a PR add a new notebook ("notebooks/foo.ipynb") and update the README
 * awesome_bot diligently checks the README and looks for https://github.com/IDR/idr-notebooks/blob/master/notebooks/foo.ipynb which will only exist when the PR is merged.

**Comment by dkhamsing** [comment]
Ahh right right.. hmm 🤔

**Comment by dkhamsing** [comment]
In your scenario, you would have a failure, and choose to ignore it. Then it would pass when the PR is merged

That's not ideal :(

**Comment by dkhamsing** [comment]
I think the current option even with a static url against master is pretty good, it will catch more links than previously was possible and alert you if you change the existing ones

I will push the release out today

**Comment by dkhamsing** [comment]
Gem version `1.16.0` published today

**Comment by dkhamsing** [comment]
@joshmoore the update only works for markdown links so don't use this with html :)

**Comment by joshmoore** [comment]
Thanks, @dkhamsing!

**Comment by dkhamsing** [comment]
:)
