### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/awesome_bot#12]
- [x] README should say 5 seconds instead of 5s
- [x] readme mention using `git diff` to use tool with new files in pr or just new changes, thanks [Richard](https://github.com/RichardLitt)!

**Comment by RichardLitt** [comment]
Looks like this can be closed?

**Comment by dkhamsing** [comment]
There is one more item, the last one

**Comment by RichardLitt** [comment]
Ah, missed that.

**Comment by dkhamsing** [comment]
Moved to https://github.com/dkhamsing/awesome_bot/projects/1

Closing
