### ISSUE TITLE
Option to not flag redirect if http changes to https or vice versa

### ISSUE THREAD

**Issue by aviaryan** [dkhamsing/awesome_bot#121]
Sites redirect from http to https and even vice versa. 
For example, see reports of https://travis-ci.org/aviaryan/awesome-no-login-web-apps/builds/182523145

I would like an option to whitelist these types of redirects as they are not a problem. 

---
Update 1: corrected link

**Comment by dkhamsing** [comment]
I would use option
  --allow-redirect  
which would ignore all redirects

**Comment by aviaryan** [comment]
Yes I know but I don't want shortlinks in my README. So I cannot go with --allow-redirects.

**Comment by dkhamsing** [comment]
I see
Seems to be very specific to your use so not sure that will be supported

Would it help if I help you update your current redirects?

**Comment by aviaryan** [comment]
> Seems to be very specific to your use so not sure that will be supported

I thought lots of people would want this type of feature in awesome-READMEs so I opened the issue. Maybe I was wrong. Nevermind, thanks for the PR. Closing this issue now.

**Comment by dkhamsing** [comment]
np

@aviaryan most people care about all redirects and fix em, or just ignore all of em

lemme know if i can help with anything else
