### ISSUE TITLE
Add silent option to remove `ab-results-README.md.json` after run

### ISSUE THREAD

**Issue by RichardLitt** [dkhamsing/awesome_bot#122]
Currently, I have to manually delete this after I run awesome_bot. Would be great if it could be automatically deleted.

**Comment by dkhamsing** [comment]
i am thinking of option `--no-results`, will not create any results files

**Comment by dkhamsing** [comment]
it will be `--skip-save-results`

**Comment by dkhamsing** [comment]
changes are in version `1.15.0`, published today
