### ISSUE TITLE
Print the whitelisted dupes

### ISSUE THREAD

**Issue by kud1ing** [dkhamsing/awesome_bot#135]
It would be nice to be informed about dupes without it meaning an error.

Whitelisted URLs via `--white-list` are printed in the output.
Whitelisted dupes via `--allow-dupe` are not printed.

So my suggestion would be to print the whitelisted dupes, too.

**Comment by dkhamsing** [comment]
Closing this. Can reopen if this is requested by more people 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
