### ISSUE TITLE
Unable to parse embedded links in markdown

### ISSUE THREAD

**Issue by RichardLitt** [dkhamsing/awesome_bot#136]
```
Issues :-(
> Links
  1. [L004] 404 https://en.wikipedia.org/wiki/Language_preservation)).
```

Here's the line which is being parsed wrongly:

> There is no centralized list of open-source code that would be useful for documenting, conserving, developing, preserving, or working with endangered languages. According to some estimates, half of the 7,000~ currently spoken languages are expected to become extinct this century ([Wikipedia](https://en.wikipedia.org/wiki/Language_preservation)). However, there is a lot of work by academics, independent scholars, organizations, communities, and individuals which goes towards stopping or slowing this trend. This list is intended to provide a central location to document those efforts.

It looks like the `)).` is messing this up. Ideas?

**Comment by dkhamsing** [comment]
It’s a bug
