### ISSUE TITLE
Markdown syntax error catching

### ISSUE THREAD

**Issue by RichardLitt** [dkhamsing/awesome_bot#139]
As far as I know, this tool is mostly used on GitHub. It doesn't catch the following error:
```[link] (link)```
Why would it? the link in the parens is fine. However, this won't render properly, and I think that a flag to catch this specific error - a space between brackets and parens - might be nice. 

I run across this syntax issue again and again with longer lists. CF https://github.com/lukasz-madon/awesome-remote-job/pull/389. 

If not here, what other module might be good to check this?

**Comment by dkhamsing** [comment]
@RichardLitt I think this will have to be an opt-in flag

**Comment by RichardLitt** [comment]
100% agreed. How about `--validate-markdown`?

**Comment by dkhamsing** [comment]
Maybe this functionality can be provided by http://danger.systems/

**Comment by dkhamsing** [comment]
Closing for now, please try Danger

**Comment by RichardLitt** [comment]
@dkhamsing Are you deprecating this repo, or just this issue?

**Comment by dkhamsing** [comment]
The issue
