### ISSUE TITLE
Incorrect header check caused by "content-encoding: deflate"

### ISSUE THREAD

**Issue by redaxmedia** [dkhamsing/awesome_bot#140]
Hello,

it seems that your bot can't handle "content-encoding: deflate" and returns a "incorrect header check" but without an error code. I didn't test against gzip and the other types.

Feel free to use my personal blog for testing:

* Working (uncached and uncompressed): https://redaxmedia.com/login
* Not working (cached and compressed): https://redaxmedia.com

Further reading:
https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Content-Encoding

**Comment by dkhamsing** [comment]
@redaxmedia hi there, sorry no time to look into this at the moment
hope it doesn't prevent you from using `awesome_bot`, I suggest you white list the problem links for now.. sorry again!

**Comment by dkhamsing** [comment]
Closing - we can reopen if more people report this issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
