### ISSUE TITLE
Allow regex-based entry format

### ISSUE THREAD

**Issue by Alkass** [dkhamsing/awesome_bot#143]
It would be cool if awesome_bot had a check that allows entry format enforcement. For instance, something like the following

```regex
--entry-format "^[*][ ]\[.*\]\(.*\)[ ]:[ ].{1,}$"
```

will have a hard set on

```
* [name](url) : description
```

And reject entries of any other format

**Comment by dkhamsing** [comment]
Do you think the tool Danger might help you do this? http://danger.systems/

**Comment by dkhamsing** [comment]
Closing for now, please try Danger. Thank you!
