### ISSUE TITLE
check if there is a valid HTTPS alternative

### ISSUE THREAD

**Issue by nschloe** [dkhamsing/awesome_bot#168]
HTTPS should be preferred over HTTP. Sometimes, web pages can be accessed via both HTTP and HTTPS. If the awesome list contains the HTTP link, and HTTPS works without errors, the bot should warn about this.

**Comment by dkhamsing** [comment]
Seems quite complex at a glance, would require splitting http links out and making additional request for https? Interesting though — historically, not sure I would have time to support this. Will keep this open for now and see if more people are interested 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Gonna close for now, can reopen if this is requested by more people. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
