### ISSUE TITLE
[Feature Request] - WhiteList URLs and Pattern in a file

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [dkhamsing/awesome_bot#169]
Hello dear friends,

Thanks for the awesome work. It would be very nice to be able to create a file like `.awesomebot.ignore` that contains all the whitelisted urls and patterns.

Passing a few URLs is not problem using command line arguments and can be cumbursome when you have to deal with 30+ links.

Any way to do this @dkhamsing  ?

Thanks  a lot,

Jonathan

**Comment by dkhamsing** [comment]
Can you share your project or just an example here pls 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DEKHTIARJonathan** [comment]
The objective would be to launch something as followed:

`awesome_bot readme.md --white-list-file: awesome-bot.ignore`

**awesome-bot.ignore**
```
doi.org
creativecommons.org
example.com
website1.com
website2.com
website3.com
website4.com
website5.com
arxiv.org/abs/
github.com/user/project/blob/master/myfile1.py
github.com/user/project/blob/master/myfile2.py
github.com/user/project/blob/master/myfile3.py
github.com/user/project/blob/master/myfile4.py
github.com/user/project/blob/master/myfile5.py
myblog.github.io/2015/05/21/my_article/
myblog.github.io/2015/05/21/my_other_article/
```

The advantage would be that it would become much more readable

**Comment by dkhamsing** [comment]
Interesting .. could you see what is done in this example https://github.com/vsouza/awesome-ios/blob/master/.travis.yml using shell variables .. would this help?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DEKHTIARJonathan** [comment]
It is a little bit better. However, it would still be hardly readable if the list becomes quite long.

```
language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
  - gem install danger
script:
  - white_list_env=doi.org,creativecommons.org,example.com,website1.com,website2.com,website3.com,website4.com,website5.com,arxiv.org/abs/,github.com/user/project/blob/master/myfile1.py,github.com/user/project/blob/master/myfile2.py,github.com/user/project/blob/master/myfile3.py,github.com/user/project/blob/master/myfile4.py,github.com/user/project/blob/master/myfile5.py,myblog.github.io/2015/05/21/my_article/,myblog.github.io/2015/05/21/my_other_article/
  - awesome_bot README.md --white-list $white_list_env
  - danger
notifications:
  email: false
```

**Comment by dkhamsing** [comment]
You know for white listing: it’s not a strict match, meaning in your case you could white list `website` or `myfile`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Oh my bad, I thought that was the real use case. Totally understand your point of view. We’ll keep this issue here and see if more people are interested. Thank you for your feedback!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DEKHTIARJonathan** [comment]
Absolutely no problem 😁
Yeah in this case it would have been quite easy as you pointed out.

All the best,

Jonathan

**Comment by dkhamsing** [comment]
Hi will close this but can reopen if it’s requested by more people 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
