### ISSUE TITLE
Travis CI failure

### ISSUE THREAD

**Issue by Cui-y** [dkhamsing/awesome_bot#178]
language: ruby
rvm: 2.4.1
before_script: gem install awesome_bot
script: awesome_bot *.md --allow 301,302 --white-list travis-ci

travis url :https://travis-ci.org/Cui-y/awesome-chrome-plugin-recommends/jobs/411189676

For the first time, you can't find the cause of the mistake and ask for help. Thank you.

**Comment by dkhamsing** [comment]
It says the failures is due to a dupe. Either use the option to allow dupes or add the url flagged to the white list

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
