### ISSUE TITLE
Support internal vs external URL distinction

### ISSUE THREAD

**Issue by erasche** [dkhamsing/awesome_bot#184]
We [html-proofer](https://github.com/gjtorikian/html-proofer) for other testing and it features a flag for `--external-only` and `--disable-external` which are incredibly useful features for us, since we know that internal URLs must succeed, and external URLs may fail due to reasons outside of our control.

If any community member has time, this would be a really useful feature to us.

**Comment by dkhamsing** [comment]
Couldn’t you achieve this with whitelisting a domain ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
