### ISSUE TITLE
Uri gem has been yanked

### ISSUE THREAD

**Issue by vredniy** [dkhamsing/awesome_bot#21]
So I cannot install this gem. Can you please fix it?

**Comment by vredniy** [comment]
https://rubygems.org/gems/uri

**Comment by dkhamsing** [comment]
Oh wow, will look into it

**Comment by dkhamsing** [comment]
@vredniy hey should be fixed, look for version `1.3.3`

**Comment by vredniy** [comment]
@dkhamsing Thanks so much for fixing it and for that wonderful tool :+1: . By the way, I'm using it https://github.com/vredniy/awesome-newsletters :smile:

**Comment by dkhamsing** [comment]
Sweet, will add you in the README

**Comment by dkhamsing** [comment]
Nice #23
