### ISSUE TITLE
Error: slideshare returning http code 999 ?

### ISSUE THREAD

**Issue by veggiemonk** [dkhamsing/awesome_bot#29]
There is a problem with slideshare.
Look at the build: https://travis-ci.org/veggiemonk/awesome-docker/builds/99070049

```
Issues :-(
> Links 
1. 999 http://www.slideshare.net/rightscale/docker-meetup-40826948
2. 999 http://www.slideshare.net/raychaser/6-million-ways-to-log-in-docker-nyc-docker-meetup-12172014
3. 999 http://www.slideshare.net/Docker
4. 999 http://www.slideshare.net/jpetazzo
The command "awesome_bot README.md --allow-dupe --allow-redirect" exited with 1.
```
And the url is actually working!

Ex: 
* http://www.slideshare.net/jpetazzo
* http://www.slideshare.net/Docker

Do you know what is the problem?

**Comment by dkhamsing** [comment]
999 is request denied

Could be slideshare does not like awesome_bot or robots in general, as opposed to a real user: for now you'd have to white list slideshare to make it pass 

Or if this is temporary, it is because it detected too many requests from the same ip: have Travis run the test again (let me know if you need help with this)

**Comment by colbywhite** [comment]
@veggiemonk, did you ever resolve this? I was playing around with it and it certainly seems temporary. I did the following in pry and got `200`s back.

```ruby
url = 'http://www.slideshare.net/Docker'
Faraday.get(url).status  # returns 200
url = 'http://www.slideshare.net/jpetazzo'
Faraday.get(url).status  # returns 200
```

But that's coming from my local IP. I guess it's possible that slideshare is blocking whatever IP travis uses. (I would assume it uses multple IPs.) Seems unlikely.

**Comment by veggiemonk** [comment]
Yes it was temporary! Thank you.
