### ISSUE TITLE
More explicit 301 errors

### ISSUE THREAD

**Issue by Kikobeats** [dkhamsing/awesome_bot#30]
I love this repository, but I think that I need more information associated in the travis logs.

instead of:

```
1. 301 http:/redirect_url
```

better something like:

```
1. 301 http://origin_url → http://redirect_url
```

**Comment by veggiemonk** [comment]
Even better, ask to replace the old url by the redirect!

**Comment by Kikobeats** [comment]
@veggiemonk AWESOME! a cli option to replace it!!! +1

**Comment by veggiemonk** [comment]
:heart:  that kind of `--fix` cli option....

**Comment by Kikobeats** [comment]
maybe `--fix` is too generic (we have 404 or other errors as well). Something like `--fix-redirect` for 301 and 302 errors.

**Comment by veggiemonk** [comment]
Good idea!
So it can have a `--fix-duplicate` too.

**Comment by Kikobeats** [comment]
:+1:

**Comment by colbywhite** [comment]
:+1: to all of this.

**Comment by dkhamsing** [comment]
good ideas guys :smile: looks like the first idea from @Kikobeats can be a starting point.. keep you posted


```
1. 301 http://origin_url → http://redirect_url
```

**Comment by dkhamsing** [comment]
Created a new issue for fixing duplicates

Closing this with the release of 1.5.0 which displays redirect locations, thanks Colby
