### ISSUE TITLE
I'm noob

### ISSUE THREAD

**Issue by joubertredrat** [dkhamsing/awesome_bot#31]
I need to add only .travis.yml on mine project or I need to add Travis CI on webhooks too?

Thanks

**Comment by dkhamsing** [comment]
You need to connect your repo to travis 

1. go to https://travis-ci.org/
2. sign on (connect using your github account)
3. turn on travis for the specific repo, i.e. `awesome-devops`

let me know if you need any help

**Comment by joubertredrat** [comment]
@dkhamsing thanks, worked fine here.

**Comment by dkhamsing** [comment]
:tada:
