### ISSUE TITLE
Add a --ignore-ssl-certificate option

### ISSUE THREAD

**Issue by unixorn** [dkhamsing/awesome_bot#44]
I was creating a travis.yml for awesome-github and ran across a link that didn't match the server cert - `https://www.gitbook.io/book/gitbookio/markdown hostname "www.gitbook.io" does not match the server certificate`

It would be great to be able to disable that check like we can disable checking for dupes.

**Comment by dkhamsing** [comment]
hmm will take a look :smile:

**Comment by colbywhite** [comment]
Just as a sidenote, someone should notify @GitBookIO about their SSL cert though. They seem to have a legit misconfiguration issue. Shows up in my browser as well.

**Comment by joubertredrat** [comment]
:+1: +1

**Comment by RichardLitt** [comment]
:+1: I am getting this for https://this-week-in-rust.org, too.

**Comment by colbywhite** [comment]
> :+1: I am getting this for https://this-week-in-rust.org, too.

Again, something seems genuinely wrong with their SSL. That site won't load in my browser. Nor curl. Someone should contact them.

**Comment by RichardLitt** [comment]
```sh
🐕  curl -I https://this-week-in-rust.org
HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Thu, 14 Jan 2016 20:49:53 GMT
Content-Type: text/html
Content-Length: 5789
Last-Modified: Tue, 12 Jan 2016 08:33:15 GMT
Connection: keep-alive
ETag: "5694ba4b-169d"
Strict-Transport-Security: max-age=15768000; includeSubdomains; preload
X-Frame-Options: deny
Frame-Options: deny
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
```

Curling this-week-in-rust seems fine.

**Comment by jakoch** [comment]
I'm running into a SSL issue, too:

```
Issues :-(
> Links 
  1. [L089]  https://igor.io/2013/02/07/composer-stability-flags.html SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure 
  2. [L090]  https://igor.io/2013/01/07/composer-versioning.html SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure 
```

I've tried to whitelisting  `igor.io`, but that doesn't do the trick. 
Unfortunately, `--ignore-ssl` or `--ignore-ssl-verify` wasn't added, yet.
It would be nice if you would push this forward and skip SSL verification for some links.

**Comment by dkhamsing** [comment]
What repo? I can help you with white listing

**Comment by jakoch** [comment]
The repo is https://github.com/jakoch/awesome-composer
I tried [whitelisting](https://github.com/jakoch/awesome-composer/commit/7f06cbc613b799a5a77d31d919f97493792c5a08), but maybe the syntax is wrong.

**Comment by dkhamsing** [comment]
Small syntax issue

**Comment by dkhamsing** [comment]
Have a work in progress version of this 

Let me know if there are more links that are causing issues with ssl

**Comment by dkhamsing** [comment]
cc @unixorn

**Comment by dkhamsing** [comment]
cc @RichardLitt

**Comment by RichardLitt** [comment]
Still getting this for this-week-in-rust:

```
14:21 ~/src/newsletter (feature/newsletter-11) * 🐕  touch test-readme.md
14:23 ~/src/newsletter (feature/newsletter-11) * 🐕  echo 'https://this-week-in-rust.org' >> test-readme.md 
14:24 ~/src/newsletter (feature/newsletter-11) * 🐕  cat test-readme.md 
https://this-week-in-rust.org
14:24 ~/src/newsletter (feature/newsletter-11) * 🐕  awesome_bot test-readme.md 
> Checking links in test-readme.md
Links to check: 1
  1. https://this-week-in-rust.org 
Checking URLs: ?

Issues :-(
> Links 
  1. [L1]  https://this-week-in-rust.org Connection reset by peer - SSL_connect 
> Dupes 
  None ✓

Wrote results to ab-results-test-readme.md.json
```

**Comment by dkhamsing** [comment]
@RichardLitt yeah this error will be fixed
will try to publish the new version today

when updated, the command is `awesome_bot test-readme.md --allow-ssl`

**Comment by dkhamsing** [comment]
@RichardLitt this is in version `1.10.0` published today

**Comment by RichardLitt** [comment]
Sweet! Thanks!
