### ISSUE TITLE
429 Too Many Requests (leads to false negative test result)

### ISSUE THREAD

**Issue by hangtwenty** [dkhamsing/awesome_bot#46]
Check out my build here. https://travis-ci.org/hangtwenty/dive-into-machine-learning/builds/102034066

```
Issues :-(
> Links 
  1. 429 https://www.quora.com/How-do-I-learn-machine-learning-1/answer/Cory-Hicks-1
  2. 429 https://www.quora.com/How-do-I-learn-machine-learning-1/answer/Xavier-Amatriain
  3. 429 https://www.quora.com/Is-it-worth-it-to-pay-9-*-49-for-a-data-science-specialization-on-Coursera/answer/Jack-Golding
  4. 429 https://www.quora.com/How-can-I-become-a-data-scientist?redirected_qid=59455
```

429 means Too Many Request. I guess Quora doesn't like how fast your requests are coming in. So a sleep might help, but could make the execution time slow ...

or perhaps, another option? `--allow-flaky`? Not sure what other HTTP codes would make sense to count as flaky and tolerate, besides 429. For now I'll have to disable my build though, because these are all valid links

**Comment by hangtwenty** [comment]
`--white-list` doesn't seem viable cos I have many Quora links ... Perhaps if whiltelist allowed for partial matche? i.e. if I put "*quora.com*"? Maybe that's a good solution?

**Comment by dkhamsing** [comment]
@hangtwenty why doesn't --white-list work for you??

**Comment by dkhamsing** [comment]
@hangtwenty --white-list should work for you, 
--white-list quora.com white lists all links matching quora.com

**Comment by dkhamsing** [comment]
@hangtwenty will update the readme, thank you

**Comment by hangtwenty** [comment]
heck yeah! :+1:
