### ISSUE TITLE
Ignore travis badge urls

### ISSUE THREAD

**Issue by ellisonleao** [dkhamsing/awesome_bot#50]
Not sure if this is expected:

```
 301 https://travis-ci.org/ellisonleao/magictools.svg?branch=master → https://api.travis-ci.org/ellisonleao/magictools.svg?branch=master
```

Can we just ignore this 301 redirect? do i need to add travis url on `--white-list` ?

**Comment by dkhamsing** [comment]
Yes

**Comment by dkhamsing** [comment]
I would add magictools.svg

**Comment by ellisonleao** [comment]
I was wondering if we could just add the travis badge url (and maybe some other badge urls) whitelisted by default. What do you think?

**Comment by dkhamsing** [comment]
Yeah it kinda sucks that the default travis badge they give is a redirect but I'm not sure it should white list anything by default.. let me think about it

Thanks!

**Comment by dkhamsing** [comment]
@ellisonleao will add a note in the readme for now

**Comment by ellisonleao** [comment]
Ok, cool. Thanks for the heads up
