### ISSUE TITLE
Add option to ignore 429 Too Many Requests

### ISSUE THREAD

**Issue by lnishan** [dkhamsing/awesome_bot#57]
As title,

I've been working on my list, and it appears rapid requests would cause certain sites (eg. Quora) to return 429 Too Many Requests (or even 403).

This is kind of troublesome. It would be nice if there's an option to ignore it.

Thanks.

**Comment by dkhamsing** [comment]
Hm yeah that is definitely an issue, thanks for the report!

**Comment by lnishan** [comment]
Thank you for the quick response :)

:+1: It's really a great tool. Really appreciate the efforts.

**Comment by colbywhite** [comment]
I would think you would get one request per url, so each url wouldn't get too many. Is your case that you have multiple urls in the same file that are either dupes or for the same host? 

I would think to trip most people's 429 threshold you'd have to have a lot of those type of urls in your file. Seems like a small edge case. An annoying one if you're ever in that scenario, but still pretty small.

Has this happened to you?

**Comment by lnishan** [comment]
It is the case with my list (20+ URLs to Quora).

I think I would agree that it's an edge case. Ignoring 429 isn't a good solution either.

How about a ignore-list? (white-list still makes HTTP requests)

**Comment by dkhamsing** [comment]
In that case maybe using the white list option is appropriate, it still checks the links but they do not count as failures

**Comment by lnishan** [comment]
:+1:
