### ISSUE TITLE
Optionally allow 301/302 status

### ISSUE THREAD

**Issue by ripienaar** [dkhamsing/awesome_bot#7]
At present urls that return 301/302 is considered a fail, I think it should be allowed as its common for sites to restructure URLs and well behaved ones would add 301 results, it's not a bad thing

**Comment by dkhamsing** [comment]
Thanks
I think it should still register as a failure but that could be skipped with an option `--allow-redirect`, what do you think?

Note: if there are urls you know about and do not care to check, you can use `--allow-white-list`

**Comment by ripienaar** [comment]
Yeah that's what I mean with optional. Enabled using a flag

I have many urls in mine that have 301/302 statuses. Many many. And I would still want to catch let's say 404s on those so whitelisting isn't an option really

**Comment by dkhamsing** [comment]
Ok got it, got something working.. I will test it with https://github.com/ripienaar/free-for-dev

**Comment by dkhamsing** [comment]
@ripienaar hey updated the gem so it can disregard redirects https://travis-ci.org/dkhamsing/travis-playground/builds/96860246

let me know if you need help with travis :wink:
