### ISSUE TITLE
405 errors

### ISSUE THREAD

**Issue by RichardLitt** [dkhamsing/awesome_bot#75]
This is on [awesome-conferences](//github.com/RichardLitt/awesome-conferences). 

```
  2. [L046] 405 http://dancejs.io/  
  3. [L056] 405 https://www.google.com/events/io  
  5. [L130] 500 http://decentralizecamp.com/  
  6. [L138] 405 https://emberfest.eu/  
```

Not sure why these aren't loading. Same for the 500 for decentralize.

**Comment by dkhamsing** [comment]
@RichardLitt thanks for the report. please white list those links as a temporary fix 😢

**Comment by RichardLitt** [comment]
Cool. I'll just wait; it's too easy to whitelist. :)

**Comment by dkhamsing** [comment]
@RichardLitt 
pushed `1.8.5` today with some fixes, closing

thanks
