### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/awesome_bot#79]
Choose and implement a command option parser

Ideally use `OptionParser` since it is part of ruby http://ruby-doc.org/stdlib-2.3.1/libdoc/optparse/rdoc/OptionParser.html 

Other contenders

- https://github.com/erikhuda/thor
- https://github.com/docopt/docopt.rb 
- https://github.com/leejarvis/slop
- https://github.com/CocoaPods/CLAide

**Comment by sotayamashita** [comment]
I have only use thor once. Does anyone know these libs ?

**Comment by dkhamsing** [comment]
@sotayamashita one problem is there is an existing option interface and user base and it would be ideal not to introduce breaking changes

We would like to support

```shell
awesome_bot <file> [--allow-dupe] [--allow-redirect] [--allow-timeout] [--set-timeout d] [--white-list item1,item2,..]
  file             Path to file, required as first argument
  --allow-dupe     Duplicate URLs are allowed
  --allow-redirect Redirected URLs are allowed
  --allow-timeout  URLs that time out are allowed
  --set-timeout    Set connection timeout (seconds)
  --white-list     Comma separated URLs/domains to white list
```

**Comment by sotayamashita** [comment]
@dkhamsing In terms of thor, I think you don't have to worry about it because it is supported cli arguments. I will implement very small sample code today.

**Comment by dkhamsing** [comment]
Ok
Thanks so much for your help, really appreciate it

**Comment by sotayamashita** [comment]
@dkhamsing I am sorry. I try to use these libs this weekend

**Comment by dkhamsing** [comment]
No rush

**Comment by dkhamsing** [comment]
Hey I was trying optparse and it should work

For you start working on it, please post here
I will do the same

**Comment by dkhamsing** [comment]
Started working on this, will keep you posted https://github.com/dkhamsing/awesome_bot/tree/cli

**Comment by sotayamashita** [comment]
@dkhamsing I have created a repo to try libs. https://github.com/sotayamashita/comparing-CLI

**Comment by dkhamsing** [comment]
Cool
Can you explain what the `start` value mean in the README

**Comment by sotayamashita** [comment]
@dkhamsing It is typo. I have already fixed.

**Comment by dkhamsing** [comment]
Oh ok

**Comment by dkhamsing** [comment]
CLI updated with `1.9.0` published today
