### ISSUE TITLE
allow to config black-list 

### ISSUE THREAD

**Issue by manuzhang** [dkhamsing/awesome_bot#90]
Say a file has some old links I'd like to replace, then a black-list will be useful to find all of them out.

**Comment by dkhamsing** [comment]
Not sure I follow.. ?

**Comment by manuzhang** [comment]
For example, I've README like

```
[old website](https://old_website.com)
some texts 
[old website](https://old_website.com)
```

Then I'd like to move to a new website while the old website is still online. I go to change the links of old website to the new website but I'm not sure whether all of them have been replaced. Hence I'd like to run
`awesome_bot --black-list https://old_website.com` to ensure no links of old website exists.

**Comment by dkhamsing** [comment]
Ah
Ok I get it

Will think about it

**Comment by dkhamsing** [comment]
Hm will you be using this in the context of ci and updating a readme ??

**Comment by manuzhang** [comment]
maybe not. It will be more like a one-shot command.

**Comment by dkhamsing** [comment]
Wouldn't you rather fire up your favorite editor and use search and replace ?

**Comment by manuzhang** [comment]
Yes, that's what I used to do. What if there are a lot of README files in a big project ?

**Comment by dkhamsing** [comment]
Hm I see
If the links in questions have redirect, they would be found by the current tool

Otherwise it's really out of scope
Closing
